### ISSUE TITLE
Additional updates for Jakarta XML Binding 3

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jaxb-tck#24]
Scanning through the content to update the user guide revealed the following issues (not all may need to be changed):
- [x] TCK Installer created folder jaxb-tck23. This should be changed to jaxb-tck30
- [x] HTML folder included in TCK Zip user guide (currently 'staging') is missing css and img folders (and their contents). Please update the zip generation script to correct this. I recommend following the same change pattern used for user guides in jakartaee-tck project.
- [x] Test and exclude file names should be updated to 30 in their file names.
- [ ] Please check if the test property tags should start with the jck prefix (i.e. jck.prolog)
- [x] Assert files in jaxb-tck/spec/2.0/* should be updated from javax to jakarta and folder should be renamed to 3.0
- [ ] Check if the contents can safely be updated by string substitution (as with several other Specs, or if this must be regenerated from new source).
- [x] Sig test description giles (doc/descriptions in: jaxb-tck/jaxb-tck/tests/api/javax_api and also the index.html in that folder) need to be updated javax->jakarta. I can handle this if simple substitution is okay).
- [x] Some html files refer to non-existent file COPYRIGHT-jaxbtck.html. I recommend simply deleting the references.
- [x] Some files still contain text referring to Reference Implementation
- [ ] Some files in ZIP archive (not exactly sure where these are located in the repository) contain text referring to 'Sun' specific features (e.g. url links in jakarta-xml-binding-tck-3.0.0.zip->JAXB-TCK-3.0.jar->Data1.zip->JAXB-TCK-3.0/tests/xml_schema/ndex.html)

**Comment by lukasj** [comment]
some items has been fixed already, some are in #37 and for the rest:

* test property tags - I'd prefer to not touch this now for EE 9 as this can be expensive (in terms of verifying this kind of change - one run to verify changes takes ~8 hours) and quite disruptive now, we can revisit this later (ie in an update)

* Assert files - it does not make much sense to me to update these files if we're not using them (building html files out of these); I'll try to check if there's anything I can do to re-enable build of these files

* string subst.- not sure I understand this item. What exactly do you mean here?

* 'Sun' specific features - do you mean 'sunData' folder? If so, I don't think that is about 'Sun' specific features since it could be just about from where the data came in (ie 'msData' - interoperability with MS or 'nistData' - could be datatypes defined by NIST)

**Comment by lukasj** [comment]
assert files fixed through #38

**Comment by lukasj** [comment]
@edbratt as for `COPYRIGHT-jaxbtck.html` - that is removed/deleted now. Do you think it should have been replaced by appropriate license file having EPL-2.0 + GPL-2.0 WITH CPE text instead?

**Comment by lukasj** [comment]
I consider things you've pointed to as done, the rest is questionable and not something we should/could fix for EE 9. If you disagree, let us know through new issue. Thanks!
